
# Expiration courte : 4h (4 heures * 60 minutes * 60 secondes * 1000 ms)
jwt.expiration=14400000

# Configuration upload fichiers
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB