spring:
  application:
    name: gestioncabinet

  datasource:
    url: jdbc:postgresql://localhost:5432/cabinet_medical
    username: postgres
    password: assia2004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  devtools:
    restart:
      enabled: true

# Configuration pour voir les erreurs complètes
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always  # IMPORTANT: Affiche la stack trace complète
    include-exception: true

# Logs détaillés
logging:
  level:
    root: INFO
    com.cabinetmedical.gestioncabinet: DEBUG
    org.springframework.web: DEBUG  # Voir les requêtes HTTP
    org.springframework.web.servlet.mvc.method.annotation: TRACE  # Voir le mapping des controllers
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.deprecation: ERROR